### ISSUE TITLE
The fractal theme could not be found error

### ISSUE THREAD

**Issue by bananenpampe** [MichaelCurrin/code-cookbook#12]
Hello, when running the github actions to deploy your page I receive a 
`github-pages 227 | Error:  The fractal theme could not be found.` and the build with jekyll step crashes.

**Comment by MichaelCurrin** [comment]
Hmm I see.

https://github.com/bananenpampe/code-cookbook/actions/runs/3370413081/jobs/5591285582

I see the external action `actions/jekyll-build-pages@v1` is unable to find the gem listed in Gemfile, though it works for my builds.

```
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv106_44e3ef

 /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/theme.rb:84:in `rescue in gemspec': The fractal theme could not be found. (Jekyll::Errors::MissingDependencyException)

 /usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'fractal' (>= 0) among 148 total gem(s) (Gem::MissingSpecError)

  Logging at level: debug
Configuration file: /github/workspace/./_config.yml
             Theme: fractal
github-pages 227 | Error:  The fractal theme could not be found.
```

I don't know what to recommend as a i can't reproduce the error myself.

**Comment by MichaelCurrin** [comment]
Also you should refer this as a it points to a repo  that does not exist
https://github.com/bananenpampe/code-cookbook/commit/914b1d27f8199cac30c9db7456f211a49542b55e

**Comment by MichaelCurrin** [comment]
My last build today passed https://github.com/MichaelCurrin/code-cookbook/actions/runs/3376326866/jobs/5603916180
